name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:
    - name: Setup Remote Management for VNC
      run: |
        # VNC bağlantılarında şifrelemeyi devre dışı bırak
        sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCAcceptsConnectionsUnencrypted -bool true
        # Remote Management servisini yeniden başlat
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
        # Ek olarak, aktif bir GUI oturumu sağlamak için Finder’ı başlat (opsiyonel)
        open -a Finder
        
    - name: Enabling Remote Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         chmod +x login.sh
         bash login.sh
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
